POST http://localhost:3000/sessions.json
Content-Type: application/json 

{
  "email": "nick123@example.com",
  "password": "password" 
}

###

POST http://localhost:3000/users.json
Content-Type: application/json 

{
  "name": "Nick",
  "email": "nick123@example.com",
  "password": "password", 
  "password_confirmation": "password"
}