json.id product.id
json.name product.name
json.price product.price
json.images product.images
json.description product.description
json.quantity product.quantity
json.created_at product.created_at
json.updated_at product.updated_at
json.supplier product.supplier
json.orders product.orders
json.categories product.categories